# General Jekyll Config
pygments: true
url: http://example.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#3498db'
# orange #F8000 blue #3498db
  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: michaelchum
    twitter: michaelchum
    hacker_news: michaelchum

  # "Hi, I'm ______"
  name: Michael Chum
  email: michaelhochum@gmail.com
  tagline: "weak opinions, strongly held"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: false
